### PR TITLE
Delete IBM and Snappy Integrations

### PR DESCRIPTION
**Pull request by tehall16**

### CODE REVIEW

**Comment by RichardJJG** [comment]
Hi, @paigecalvert , the story for this ended up on the Services board, even though I'm guessing this repo belongs to Core (if anyone).
If you know the background for this commit (and that it makes sense), just let me know and I'll tell Samia to accept the story.

**Comment by snneji** [comment]
I think this should be in the partners Tracker. I'll move the story over.

**Comment by snneji** [comment]
I think this PR should have gone into the partners Tracker. @tehall16 do you know if I should move the PR story over there? Also, should we update the gitbot integration for this repo to send PRs to the Partners tracker automatically?

**Comment by tehall16** [comment]
@snneji that's fine with me if we send this specific one over to Partners, but what about when updating Pivotal/VMware products?

**Comment by tehall16** [comment]
Sure moving it to the Partners tracker should be fine!

**Comment by snneji** [comment]
I've moved the story and updated the gitbot integration to ensure future PRs for this repo go directly to the Partners tracker.

**Pull request merged**
