### PR TITLE
Revises mule subnav for 1.5.1

### PR DESCRIPTION
**Pull request by sleslie23**
Here is the corresponding PR for the subnav. Sorry for the delay!

### CODE REVIEW

**Comment by sleslie23** [comment]
See also: https://github.com/pivotal-cf/docs-mulesoft-anypoint/pull/5#issuecomment-283491717

**Comment by jncd** [comment]
Thanks @sleslie23 (When do the links to your docs go live?)

**Comment by sleslie23** [comment]
Thanks Jane Day! I'm not sure, but probably sometime next week. I'll find
out!

**Comment by jncd** [comment]
At least those 404s don't break our builds.
So maybe it doesn't matter.

**Comment by sleslie23** [comment]
.

**Comment by sleslie23** [comment]
Hey Jane! We are going to add a temporary redirect to avoid the 404s. Our docs will be live on Monday.

**Pull request merged**
